flowchart TD
    mh[%mh] --> rz
    nd[%nd] --> jx
    xt[%xt] --> cx
    dp[%dp] --> mh
    pz[%pz] --> zg & bf
    rp[%rp] --> jb & bf
    jb[%jb] --> bf & kp
    rj[%rj] --> xt & cx
    hg[%hg] --> dl & bf
    pt[%pt] --> gm & vv
    pf[%pf] --> xk & qr
    cv[%cv] --> jp & cx
    zg[%zg] --> bb
    qn[%qn] --> gm & bh
    kp[%kp] --> pz
    kg[%kg] --> gm & pt
    sl[%sl] --> rp
    dz[%dz] --> bf & dc
    hm[%hm] --> cx & tz
    dc[%dc] --> fk
    xk[%xk] --> qr & sf
    %% kr([&kr]) --> gf
    bq[%bq] --> qr & mg
    sf[%sf] --> qr
    cx([&cx]) --> ff & vx & zs
    hr[%hr] --> fq & gm
    ls[%ls] --> lf & gm
    mf[%mf] --> cx & sx
    vq[%vq] --> gm
    sx[%sx] --> cx & rj
    gm([&gm]) --> kg & kf & fq & nc & lf
    jx[%jx] --> qr & zz
    tz[%tz] --> mf & cx
    jp[%jp] --> cx & kt
    bb[%bb] --> hg & bf
    zz[%zz] --> pf & qr
    qr([&qr]) --> dp & bq & nd & rz & mg & qk & mh
    nc[%nc] --> gb
    kt[%kt] --> hm & cx
    mg[%mg] --> dp
    dl[%dl] --> bf
    %% zs([&zs]) --> gf
    bf([&bf]) --> dz & zg & kr & sl & fk & kp & dc
    bh[%bh] --> vq & gm
    %% kf([&kf]) --> gf
    fq[%fq] --> qn
    vl[%vl] --> vx & cx
    %% qk([&qk]) --> gf
    fk[%fk] --> sl
    tj[%tj] --> nd & qr
    gb[%gb] --> ls & gm
    lf[%lf] --> hr
    vx[%vx] --> cv
    ff[%ff] --> vl & cx
    %% b((broadcaster)) --> kg & dz & ff & bq
    vv[%vv] --> nc & gm
    %% gf([&gf]) --> rx
    rz[%rz] --> tj